### ISSUE TITLE
Changing font size

### ISSUE THREAD

**Issue by fragfaq** [r52/PTA#18]
Please make it possible to change the font size. For the usual resolution of 1920 * 1080, it is [too small](https://i.imgur.com/yoheRBg.jpg). Your program helps me a lot, but my eyes suffer (
P.s. Thank you for you work

**Comment by r52** [comment]
Feature added in d1edf5c. Edit `stylesheet/statdialog.qss` to set your custom styles.

To increase font size for example, add to the file:

```
QLabel, QCheckBox {
    font-size: 15px;
}
```

**Comment by fragfaq** [comment]
> Feature added in [d1edf5c](https://github.com/r52/PTA/commit/d1edf5ca2366bef01065bcc2c4d41204b51ddcd6). Edit `stylesheet/statdialog.qss` to set your custom styles.
> 
> To increase font size for example, add to the file:
> 
> ```
> QLabel, QCheckBox {
>     font-size: 15px;
> }
> ```

Great, TY!
