### ISSUE TITLE
Failed to download base item data

### ISSUE THREAD

**Issue by fragfaq** [r52/PTA#2]
Critical Error in starrt program. Downloading API data.... and next MsgBox Failed to download base item data.
![OMMFT4Q 1](https://user-images.githubusercontent.com/19280892/69009884-2471eb00-0984-11ea-838c-f65f67f0a347.png)
Run with administrator not help

**Comment by r52** [comment]
Fixed in the [latest build](https://ci.appveyor.com/project/r52/pta/build/artifacts).
