### ISSUE TITLE
Build issue with VS 2019

### ISSUE THREAD

**Issue by djinnsynth** [r52/PTA#33]
Trying to build PTA with VS and it keeps telling me "ERROR running qmake"

I made sure I had the most up to date Qt and the Qt extension for VS but it's still not working?

**Comment by r52** [comment]
The project files are set to look for Qt 5.12.7 at the specific path `C:\Qt\5.12.7\msvc2017_64`. If you do not have this version installed at that location, it will fail. You can change the project setting to build against another version of Qt that you have, but note that the search UI's IPC library currently only targets Qt 5.12 and __WILL NOT__ work with other versions.

**Comment by djinnsynth** [comment]
Turns out I actually had a different version but I'll give it a go again with what you said.

Thanks mate!
