### ISSUE TITLE
Failed to retrieve item text from clipboard. Please try again

### ISSUE THREAD

**Issue by gixxpunk** [r52/PTA#5]
At second use (STRG+D) I get this error all the time. Only works once for me.

**Comment by r52** [comment]
The clipboard handling code in PTA has recently been rewritten to catch _all_ clipboard events and filter on those coming from the PoE window. If you are getting that error message, it means that by the time it is PTA's turn to check the clipboard contents, it is already gone. There are a variety of reasons how this could happen.

First, please verify whether or not the clipboard is actually empty after seeing the error message by pasting into a text editor. If there is in fact item text in your clipboard even after seeing the error message, report back with the item text.

In the case that your clipboard is in fact empty after seeing the error message, and PTA is not the only tool that you run, try using PTA alone to ensure that the other tools are not consuming/erasing the item text in the clipboard before PTA gets to it.

**Comment by gixxpunk** [comment]
Hi, I'm running POE Trades Companion alongside your tool. Disabling it is not an option. If you think this is what causes the problem I will sadly have to switch back to POE TradeMacro,

This is the clipboard content I have while I get the error:

```
Rarity: Unique
Rumi's Concoction
Granite Flask
--------
Quality: +24% (augmented)
Lasts 5.00 (augmented) Seconds
Consumes 30 of 60 Charges on use
Currently has 60 Charges
+3000 to Armour
--------
Requirements:
Level: 68
--------
Item Level: 73
--------
+17% Chance to Block Attack Damage during Flask effect
+9% Chance to Block Spell Damage during Flask effect
--------
"Yesterday I was clever, so I wanted to change the world.
Today I am wise, so I am changing myself."
-Rumi of the Vaal
--------
Right click to drink. Can only hold charges while in belt. Refills as you kill monsters.
```

Looks correct to me.

**Comment by gixxpunk** [comment]
I think I found the problem. It was indeed POE Trades Companion. There is an option called "Hold CTRL when copying trading whisper to instantly send in game?"

This one seems to cause the problems. Disabled it now. So far so good.

**Comment by r52** [comment]
Hey, thanks for investigating. Hopefully disabling that option fixes it for good. If it is indeed the case, I'll have a look in the next little while to see if I can get PTA to play nice with that option in PoE Trade Companion, as it seems like you aren't the only one with this issue.
